from archinfo.arch import Arch, Register, register_arch
from archinfo.types import Endness, RegisterOffset

# This file is autogenerated with the `arch-genesys` tool
# project name: vmwhere
# date: 2024-06-05T17:08:28.242670+00:00

class ArchVMWHERE(Arch):

    memory_endness = Endness.LE
    bits = 64
    vex_arch = None
    name = "vmwhere"
    instruction_alignment = 1

    # registers is a dictionary mapping register names, to a tuple of
    # register offset, and their width, in bytes

    register_list = [
        Register(name="ip", size=8, vex_offset=0, alias_names=['pc'],),
        Register(name="bp", size=8, vex_offset=8,),
        Register(name="sp", size=8, vex_offset=16,),
        Register(name="sysnum", size=8, vex_offset=24,),
        Register(name="ip_at_syscall", size=8, vex_offset=32,),
    ]

    ip_offset = RegisterOffset(0)
    sp_offset = RegisterOffset(2)

    def __init__(self, endness=Endness.LE):
        self.cs_mode = None
        super().__init__(Endness.LE)


register_arch(['vmwhere|VMWHERE'], 64, Endness.LE, ArchVMWHERE)
